name: Get Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Script
      run: |
        python get_data.py
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'actions@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add .
        git commit -m "[Github Action] Update data"
        git push origin HEAD:${{ github.ref }}
